### ISSUE TITLE
Crash when reading line

### ISSUE THREAD

**Issue by haralduna** [frizbog/gedcom4j#184]
java.lang.ArrayIndexOutOfBoundsException: 
  at org.gedcom4j.io.reader.AnselReader.nextLine(AnselReader.java:151)
  at org.gedcom4j.io.reader.GedcomFileReader.nextLine(GedcomFileReader.java:120)
  at org.gedcom4j.parser.GedcomParser.load(GedcomParser.java:325)

151:                        holdingBin[holdingBinIdx++] = (char) twoCharsBack;

The holdingBin array has a size of two, and the code clearly allows the index to take a value greater than two. Could you give some advice on fixing this, maybe by adding a safeguard?

**Comment by FlorianCassayre** [comment]
Same issue on my side and also wondering how to fix it.

Edit: it seems that the file I was trying to read was using an ANSI encoding scheme (but the parser decided to decode it as ANSEL because the charset was not specified in the header).
