### ISSUE TITLE
null pointer error in Individual.getAttributesOf Type 

### ISSUE THREAD

**Issue by gjwo** [frizbog/gedcom4j#189]
Can't see what's going wrong here, I get this error on some individuals (presumably those with no attributes) it works OK for others. is there something I should check before the call?

> 865 [Thread-0] INFO org.eclipse.jetty.server.Server - Started @1698ms
> 4079 [qtp2104434427-16] ERROR spark.http.matching.GeneralError - 
> java.lang.NullPointerException
> 	at org.gedcom4j.model.Individual.getAttributesOfType(Individual.java:586)
>     
>     line appears to be  IndividualAttribute ir = (IndividualAttribute)var3.next(); see below
>      
> 	at me.gjwo.gedcom.FactPicker.getIndAttributeTableData(FactPicker.java:111)
> 	at me.gjwo.gedcom.pages.elements.PersonAttributesElement.render(PersonAttributesElement.java:36)
> 	at me.gjwo.gedcom.pages.IndividualPage.render(IndividualPage.java:44)
> 	at me.gjwo.gedcom.GedcomView.lambda$main$2(GedcomView.java:46)
> 	at spark.RouteImpl$1.handle(RouteImpl.java:72)
> 

```
    public List<IndividualAttribute> getAttributesOfType(IndividualAttributeType type) {
        List<IndividualAttribute> result = new ArrayList(0);
        Iterator var3 = this.attributes.iterator();

        while(var3.hasNext()) {
           IndividualAttribute ir = (IndividualAttribute)var3.next();
            if (ir.getType() == type) {
                result.add(ir);
            }
        }

        return result;
    }

```

**Comment by gjwo** [comment]
OK I think the whole collection is null, which I have now tested for now to avoid crashing. It would be much better generally of you could enhance your library to initialise your data structures to the appropriate empty Collections rather than null if you find no data for a collection in the .ged file. This would avoid all sorts of issues and for each loops would work as intended.

**Comment by frizbog** [comment]
This was a deliberate design decision to reduce memory footprint especially
on mobile devices that have very strict limits on heap size. The library
actually used to do what you suggest and it typically wasted about 60% of
the heap utilization on empty collections.  The getters for collections on
all objects are overloaded so if you say object.getCollection(true), it
will initialize the collection to an empty list if needed before
returning.

**Comment by frizbog** [comment]
Yes it does!

**Comment by gjwo** [comment]
Excellent!

**Comment by gjwo** [comment]
This seems to work for getEvents(true) of both types, but not for getEventsOfType(... which throws a compile error.

**Comment by frizbog** [comment]
Ok looks like I missed one. It's the getters and setters of the model
properties that do that optional initialization.

**Comment by gjwo** [comment]
It is the "getEventsOfType" calls that I use the most (as caused the null pointer problem at the top of this thread) I wouldn't normally use the "getEvent" first I think the only time was when I implemented the missing Family,getEventsOfType method. So I would say the "getEventsOfType" most need to be initialised with empty sets if required.
