### ISSUE TITLE
Tests fail; won't compile under JDK19

### ISSUE THREAD

**Issue by davejbur** [frizbog/gedcom4j#209]
Two of the tests fail under JDK19 (jdk-19.0.2+7) (they work fine under the latest JDK8 - jdk8u362-b09).

```
Running org.gedcom4j.writer.GedcomWriterFileProgressAndCancellationTest
Tests run: 14, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 18.742 s <<< FAILURE! - in org.gedcom4j.writer.GedcomWriterFileProgressAndCancellationTest
org.gedcom4j.writer.GedcomWriterFileProgressAndCancellationTest.testNoCancellationUtf8Crlf  Time elapsed: 0.251 s  <<< FAILURE!
java.lang.AssertionError: expected:<581632> but was:<584192>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at org.gedcom4j.writer.GedcomWriterFileProgressAndCancellationTest.testNoCancellationUtf8Crlf(GedcomWriterFileProgressAndCancellationTest.java:530)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:398)
	at org.apache.maven.surefire.junitcore.pc.InvokerStrategy.schedule(InvokerStrategy.java:54)
	at org.apache.maven.surefire.junitcore.pc.Scheduler.schedule(Scheduler.java:355)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:398)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)

org.gedcom4j.writer.GedcomWriterFileProgressAndCancellationTest.testNoCancellationUtf8CrOnly  Time elapsed: 0.563 s  <<< FAILURE!
java.lang.AssertionError: expected:<557056> but was:<563712>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at org.gedcom4j.writer.GedcomWriterFileProgressAndCancellationTest.testNoCancellationUtf8CrOnly(GedcomWriterFileProgressAndCancellationTest.java:571)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:398)
	at org.apache.maven.surefire.junitcore.pc.InvokerStrategy.schedule(InvokerStrategy.java:54)
	at org.apache.maven.surefire.junitcore.pc.Scheduler.schedule(Scheduler.java:355)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:398)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)


Results:

Failures: 
  GedcomWriterFileProgressAndCancellationTest.testNoCancellationUtf8CrOnly:571 expected:<557056> but was:<563712>
  GedcomWriterFileProgressAndCancellationTest.testNoCancellationUtf8Crlf:530 expected:<581632> but was:<584192>

```

I'm not sure what the problem is, I can't see what the test is trying to do! (why write to a null output stream? possibly writing to a real file might indicate where the issue lies?)

**Comment by davejbur** [comment]
Compiles no problem under jdk-17.0.6+10

**Comment by davejbur** [comment]
Is this rather useful utility actually maintained any more? I'm the last one to have added anything, and that was 2.5 years ago!

Anyway, I've been doing some more tests - I have determined that the issue arises somewhere between JDK18 & JDK19, and it looks like it boils down to the difference in buffer size between the two. Up to JDK18, the buffer size was always 8192 bytes; after that, it is variable, and in these unit tests it appears to be 512 bytes.

The problem is that the Utf8Writer (which is actually doing the writing) only notifies progress every 500 lines, and it's the last notification event that's being tested against. The file being written is 607893 bytes (in Windows, anyway, with CRLF line endings), and 20945 lines long. So the last notification gets sent after 20500 lines.

Up to and including JDK18, FileProgressListener gets to 581632 bytes (i.e. 71 x 8192).
For JDK19 and later, FileProgressListener gets to 584192 bytes (i.e. 1141 x 512).

Incidentally, in both cases, I'm compiling for JDK17 - so, to my mind, there's some problem in the JDK itself, since, whatever the version of the JDK, compiling *for* an earlier version should be indistinguishable from compiling *with* that earlier version.

Since we apparently can't, except by experiment, know for sure what the buffer size is, we can't sensibly predict what bytesWritten will be after 500 lines. In any case, I would have thought that the FileProgressListener should be getting to the total file size on completion, regardless of the buffer size.

For both those reasons, and for the fact that it looks like it's only me playing with this right now:-) I propose commenting out the offending test in line 530 of `GedcomWriterFileProgressAndCancellationTest`, `assertEquals(581632, bytesWritten);`

**Comment by davejbur** [comment]
Incidentally, the next test down also fails under JDK19+.

Line 571 `assertEquals(557056, bytesWritten);` has to be commented out.

**Comment by andreas1974** [comment]
> Is this rather useful utility actually maintained any more? I'm the last one to have added anything, and that was 2.5 years ago!
> 

Since you ask I just want to say that I agree, its a useful utility.

In 2018 I made a program that cleans up GEDCOM files. The program removes unnecessary notes, problematic for the reports in Genbox FamilyHistory, which I sometimes use just for the sake of its nice reports (instead of my regular genealogy program). So I run this program on the gedcom file first, before importing to Genbox. In that way I still _use_ Gedcom4j, but I haven't updated the component in a long time, and I take no part in maintaining it. Thank you for taking care of it!
